### ISSUE TITLE
how to Extract training images

### ISSUE THREAD

**Issue by Mlt123** [foamliu/Deep-Image-Matting-v2#21]
7plus@7pluss-MacBook-Pro ~ % python pre_process.py  
python: can't open file 'pre_process.py': [Errno 2] No such file or directory

So how to deal with it？

**Comment by Mlt123** [comment]
Where should the obtained dataset be placed?

**Comment by Mlt123** [comment]
7plus@7pluss-MacBook-Pro Deep-Image-Matting-PyTorch-master % python pre_process.py

Traceback (most recent call last):
  File "pre_process.py", line 8, in <module>
    from Combined_Dataset.Training_set.Composition_code_revised import do_composite
  File "/Users/7plus/opt/anaconda3/Deep-Image-Matting-PyTorch-master/Combined_Dataset/Training_set/Composition_code_revised.py", line 5, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'

**Comment by Mlt123** [comment]
7plus@7pluss-MacBook-Pro Deep-Image-Matting-PyTorch-master % python pre_process.py   
 
Extracting data/Adobe_Deep_Matting_Dataset.zip...
Traceback (most recent call last):
  File "pre_process.py", line 27, in <module>
    zip_ref = zipfile.ZipFile(zip_file, 'r')
  File "/Users/7plus/opt/anaconda3/lib/python3.7/zipfile.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/Adobe_Deep_Matting_Dataset.zip'
