### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by Mlt123** [foamliu/Deep-Image-Matting-v2#22]
/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py:435: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "demo.py", line 69, in <module>
    checkpoint = torch.load(checkpoint)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 505, in persistent_load
    data_type(size), location)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 114, in default_restore_location
    result = fn(storage, location)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

**Comment by Snow-Willow** [comment]
pytorch 1.1.0 cannot  install

**Comment by Mlt123** [comment]
7plus@7pluss-MacBook-Pro Deep-Image-Matting-PyTorch-master % python demo.py

/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.parallel.data_parallel.DataParallel' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py:493: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "demo.py", line 69, in <module>
    torch.load(checkpoint, map_location=lambda storage, location: 'cpu')
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 135, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/Users/7plus/opt/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 130, in _rebuild_tensor
    t = torch.tensor([], dtype=storage.dtype, device=storage.device)
AttributeError: 'str' object has no attribute 'dtype'

**Comment by foamliu** [comment]
The solution is in your error message: "If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU."
